/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          primary: '#5046e5',
          gradientStart: '#4f46e5',
          gradientEnd: '#7c3aed',
        },
        primary: {
          DEFAULT: '#5046e5',
          container: '#4338ca',
          fixed: '#e0e7ff',
          'fixed-dim': '#c7d2fe',
        },
        'on-primary': '#ffffff',
        'primary-container': '#4338ca',
        'on-primary-container': '#e0e7ff',
        'primary-fixed': '#e0e7ff',
        'on-primary-fixed': '#312e81',
        secondary: '#64748b',
        'on-secondary': '#ffffff',
        'secondary-container': '#f1f5f9',
        'on-secondary-container': '#334155',
        tertiary: '#7c3aed',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#ede9fe',
        error: '#ef4444',
        'error-container': '#fee2e2',
        'on-error': '#ffffff',
        'on-error-container': '#991b1b',
        background: '#f8fafc',
        'on-background': '#0f172a',
        surface: '#ffffff',
        'on-surface': '#0f172a',
        'surface-variant': '#f1f5f9',
        'on-surface-variant': '#475569',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f8fafc',
        'surface-container': '#f1f5f9',
        'surface-container-high': '#e2e8f0',
        'surface-container-highest': '#cbd5e1',
        'surface-tint': '#6366f1',
        'outline-variant': '#e2e8f0',
        outline: '#94a3b8',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'Inter', 'system-ui', 'sans-serif'],
        display: ['Outfit', '"Plus Jakarta Sans"', 'sans-serif'],
      },
      borderRadius: {
        '3xl': '24px',
        '4xl': '32px',
      },
      boxShadow: {
        'glass': '0 20px 40px -15px rgba(99, 102, 241, 0.12)',
        'card': '0 4px 20px -2px rgba(15, 23, 42, 0.05)',
        'phone': '0 25px 60px -15px rgba(15, 23, 42, 0.25), 0 0 0 12px #1e293b, 0 0 0 14px #475569',
      }
    },
  },
  plugins: [],
};
